### ISSUE TITLE
工作流类型的AI应用，由于接口没返回text_chunk事件类型，导致前端没法展示

### ISSUE THREAD

**Issue by unmurphy** [lexmin0412/dify-chat#282]
### 清晰简洁的问题描述

工作流类型的AI应用，由于接口没返回text_chunk事件类型，导致前端没法展示

![Image](https://github.com/user-attachments/assets/26a1538e-168d-47d2-afe4-bd387f4ad46c)

```yaml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: 测试
  use_icon_as_answer_icon: false
dependencies: []
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: template-transform
      id: 1747648132903-source-1747648141451-target
      source: '1747648132903'
      sourceHandle: source
      target: '1747648141451'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: template-transform
        targetType: end
      id: 1747648141451-source-1747648158515-target
      source: '1747648141451'
      sourceHandle: source
      target: '1747648158515'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables:
        - label: aa
          max_length: 48
          options: []
          required: true
          type: text-input
          variable: aa
      height: 90
      id: '1747648132903'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        selected: false
        template: 天色黄昏，一群乌鸦落在枯藤缠绕的老树上，发出凄厉的哀鸣。小桥下流水哗哗作响，小桥边庄户人家炊烟袅袅，古道上一匹瘦马，顶着西风艰难地前行。夕阳渐渐地失去了光泽，从西边落下。凄寒的夜色里，只有孤独的旅人漂泊在遥远的地方
        title: 模板转换
        type: template-transform
        variables: []
      height: 54
      id: '1747648141451'
      position:
        x: 384
        y: 282
      positionAbsolute:
        x: 384
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1747648141451'
          - output
          variable: output
        selected: false
        title: 结束
        type: end
      height: 90
      id: '1747648158515'
      position:
        x: 688
        y: 282
      positionAbsolute:
        x: 688
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -158
      y: 100.5
      zoom: 1
```

### 使用的 Dify 版本

v1.0.1

### 可重现问题的 DSL 链接

已粘贴

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
    Memory: 8.25 GB / 31.68 GB
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (133.0.3065.69)
    Internet Explorer: 11.0.26100.1882
```

### 运行环境

Docker

### 验证项

- [x] 检查是否已经存在相同的 issue，避免创建重复问题。
- [x] 确认这是一个具体的 Bug。
- [x] 提供的 DSL 是该 Bug 的 [最小可复现示例](https://stackoverflow.com/help/minimal-reproducible-example)。
